name: Post pulodev content daily

on: [push]
# schedule:
# - cron: '*/5 * * * *'

jobs:
  post-content:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Run code
        run: pnpm job
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SUPA_URL: ${{ secrets.SUPA_URL }}
          SUPA_KEY: ${{ secrets.SUPA_KEY }}
          SUPA_TABLE: ${{ secrets.SUPA_TABLE }}
          SUPA_TABLE_CONFIG: ${{ secrets.SUPA_TABLE_CONFIG }}
